---
title: "Ejemplo de relleno usando ePCA"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:
  html_document: default
#  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Departamento de Redes y Procesamiento de Datos 
##Instituto Meteorológico Nacional 
##Dr. José Luis Araya López

Este tutorial es una descripción de cómo debe de usarse el código para procesar los datos en su totalidad y obtener productos
de datos rellenados usando el algoritmo ePCA
 

```

rm(list = ls())


#import Libraries
library("plyr")


source("/home/jlaraya/Documents/BaseEspejo/codigo/funciones.R")
ruta<-"/home/jlaraya/Documents/BaseEspejo/reportesDiariosYMensuales/datos"
setwd(ruta)
print(dir())
files=dir()
opcion<-menu(0)
if(opcion==1|4 ){encab=c("CUENCA","ESTACION","FECHA","HORA","DATOS")}
#if(opcion==4){encab=c("CUENCA","ESTACION","FECHA","HORA","DATOS")}
caracter_separador=","
guardeEn="../datos2/mod_"

```

1) se cargan los datos bajados de la base de datos y se reemplaza
el caracter de separacion a forma columnar:

```
cambiando_separadores(files,caracter_separador,guardeEn)
```

2) Se separa todo el archivo con las series juntas en archivos
de datos individuales por numero de estación y cuenca:

```
setwd("../datos2")
print(dir())
files=dir()
require(readr)
library(lubridate)
#temperatura:
separe_series(files[1])

```


3) Se completa el eje de tiempo:

```
files=dir()
files=selectSomeFiles(files,1,9,"separados",".txt")
timeSpan_hours=55000
starting_date="2013-01-01 UTC"
saveHere="../datos3/ejeCompleto"
estadisticas_ejeCompleto=completar_ejeTemporal(files,timeSpan_hours,starting_date,saveHere) 
write.table(as.data.frame(estadisticas_ejeCompleto), file="../datos3/estadAll.txt",row.names = F,col.names=TRUE)

```




Ahora vamos con los cálculos de los reportes:


```
print("se cargan los datos en carpeta --datos3-- ")
ruta<-"/home/jlaraya/Documents/BaseEspejo/reportesDiariosYMensuales/datos3/"
setwd(ruta)
opcion<-menu(0)
print(dir())
lista<-dir()
lista=selectSomeFiles(lista,1,11,"ejeCompleto",".txt")
resol<-"day"
rutaFinal <-"../resultados/"
```


Cálculo de Promedios diarios de temperatura
Cálculo de Totales diarios de lluvia horaria

```
reso<-"hour"  #resolución de los datos originales
guardeEn <-"../resultadosDay/"
prefijo="Auto_Dia-"
resol<-"day"
diviHora<-1
if(opcion==1){Calculo= "promedio"}
if(opcion==4){Calculo= "total"}
tipoRep<-"todo"
reportesD_Q_M_Y(lista,opcion,reso,resol,guardeEn,Calculo,prefijo,tipoRep)
```


Cálculo de Promedios quincenales de temperatura
Cálculo de Totales diarios de lluvia horaria
```
guardeEn <-"../resultadosWeek/"
prefijo="Auto_Semanal-"
resol<-"week"
reportesD_Q_M_Y(lista,opcion,reso,resol,guardeEn,Calculo,prefijo,tipoRep)
```


Cálculo de Promedios mensuales de temperatura
Cálculo de Totales diarios de lluvia horaria

```
guardeEn <-"../resultadosMes/"
prefijo="Auto_Mensual-"
resol<-"month"
reportesD_Q_M_Y(lista,opcion,reso,resol,guardeEn,Calculo,prefijo,tipoRep)
```


Cálculo de Promedios anuales de temperatura
Cálculo de Totales diarios de lluvia horaria

```
guardeEn <-"../resultadosYear/"
prefijo="Auto_anual-"
resol<-"year"
reportesD_Q_M_Y(lista,opcion,reso,resol,guardeEn,Calculo,prefijo,tipoRep)
```
#######################################
#Definiendo la matriz espacio-temporal:
#######################################

```
if(opcion==1){# para temperatura horaria se pueden rellenar los datos horarios...
              par_time="tempH_x"
              ruta<-"/home/jlaraya/Documents/BaseEspejo/reportesDiariosYMensuales/datos3"
              setwd(ruta);rint(dir());files=dir()
              files=selectSomeFiles(files,1,11,"ejeCompleto",".txt")
              fechas=read.table(files[1],header=TRUE,row.names=NULL)
              fechas=subset(fechas,select=HORA:AGNO)
              datosAll=MegaMatrix(ruta,files,9)   #OJO: verificar que la columna 9 es la correcta, cambié esto posteriormente 
}
```
Para el caso de lluvia:

```

if(opcion==4){# para precipiación se pueden rellenar los datos totales mensuales
              par_time="lluvMes_x"
              ruta<-"/home/jlaraya/Documents/BaseEspejo/reportesDiariosYMensuales/resultadosMes"
              setwd(ruta);print(dir());files=dir()
              files=selectSomeFiles(files,1,19,"-total-Auto_Mensual",".txt")
              f=read.table(files[1],header=TRUE,row.names=NULL)
              fechas=as.Date(as.character(f$redond))
              fechas=as.data.frame(cbind(day=format(fechas,"%d"),month=format(fechas,"%m"),year=format(fechas,"%Y")))
              datosAll=MegaMatrix(ruta,files,7)
}
```

Se salvan los resultados...

```
write.table(datosAll, file=paste("../datosTodos/datosAll_",par_time,".txt",sep=""),row.names = F,col.names=TRUE)
write.table(fechas, file=paste("../datosTodos/fechas_datosAll_",par_time,".txt",sep=""),row.names = F,col.names=TRUE)
```


Extrayendo grupos de datos basados en criterio de distancia:


```
library(maps)
library(mapdata)
library(fields)
data(worldMapEnv)



ruta<-"/home/jlaraya//Documents/BaseEspejo/codigo/"
setwd(ruta)
nomina=read.csv("nomina_final.txt",sep="")
nomina$LONDEC=-1*nomina$LONDEC
###########
#parametros
TIPO="U"
###########

latLon=nomina[which(nomina$TIPO==TIPO),]
rownames(latLon)=paste("h",as.character(latLon$CUENCA),as.character(latLon$ESTACION),sep="_")
latLon2=subset(latLon,select=c("LONDEC","LATDEC","ALTITUD"))
write.table(latLon2, file="latLon2.txt",row.names = T,col.names=T)

####################
latDelta_inf=0.0
latDelta_sup=0.0
lonDelta_inf=0.0
lonDelta_sup=0.0
#####################

pdf("map.pdf")
map('world',xlim=c(min(latLon$LONDEC)-lonDelta_inf,max(latLon$LONDEC)+lonDelta_sup),ylim=c( (min(latLon$LATDEC)-latDelta_inf), (max(latLon$LATDEC)+latDelta_sup)),boundary=TRUE, fill=TRUE,col="yellow")
points(as.numeric(as.character(latLon2$LONDEC)), as.numeric(as.character(latLon2$LATDEC)), pch=16, col="red", cex=0.5) 
map.axes(cex.axis=0.6)
title(paste("Distribución espacial de estaciones meteorológicas tipo",TIPO,sep=" "))
dev.off()

```




GRUPOS POR DISTANCIAS

```
ruta<-"/home/jlaraya//Documents/BaseEspejo/reportesDiariosYMensuales/grupos_datos/"
setwd(ruta)
dist_m = CalcDists(latLon2)
write.table(dist_m, file="matriz_distancias.txt",row.names = T,col.names=T)
#selecting the clusters of close station from the distance matrix...R<60
########################
#DEFINA RADIO DE INFLUENCIA
radio_km=60
n_min=0
########################
inventarioGrupos=groups_reports(dist_m,radio_km,n_min)
inventarioGrupos=as.data.frame(inventarioGrupos)
write.table(inventarioGrupos, file="inventarioGrupos.txt",row.names = F,col.names=TRUE)
```

usando los datos de la corrida:

```
ruta<-"/home/jlaraya//Documents/BaseEspejo/reportesDiariosYMensuales/datosTodos/"
setwd(ruta)
files=dir()

data=read.table(selectSomeFiles(files,1,8,"datosAll",".txt"),header=T)
fechas=read.table(selectSomeFiles(files,1,6,"fechas",".txt"),header=T)
write.table(fechas, file="fechas.txt",row.names = F,col.names=TRUE)
data=data[,2:ncol(data)]
data2=na.omit(data)
print(dim(data))
print(dim(data2))

seriesNomina=paste("h",nomina$CUENCA,nomina$ESTACION,sep="_")  #series de toda la nomina
seriesActuales=names(data)#las series del lote de datos que se extrajo de la base de datos
seriesGrupos=as.character(inventarioGrupos$nameFile)  #Grupos de estaciones calculados a partir de la nómina
```

nos vamos a la carpeta de los grupos:


```
ruta<-"/home/jlaraya//Documents/BaseEspejo/reportesDiariosYMensuales/grupos_datos/"
setwd(ruta)
files=dir()
files=selectSomeFiles(files,1,9,"closeStat",".txt")  # coincide con inventarioGrupos
```
seriesActuales:estaciones existentes en la megamatriz de datos...
```
seriesEnNomina=seriesNomina[na.omit(match(seriesNomina,seriesActuales))] #las estaciones da la megamatriz que si estan en la nómina
seriesNO_nomina=seriesActuales[which(is.na(match(seriesActuales,seriesNomina)))]  #las estaciones de la megamatriz que No están en la nómina
```
¿cuales grupos coinciden con los datos que se van a analizar?

```
Los grupos que corresponden con las columnas del archivo "data" o "series actuales"
grupos_en_seriesActuales=seriesActuales[na.omit(match(seriesGrupos,seriesActuales))]
```

los grupos que no corresponden con las columnas del archivo "data" o "series actuales"

```
grupos_noen_seriesActuales=seriesGrupos[which(is.na(match(seriesGrupos,seriesActuales)))]
```
las series actuales que están en grupos:

```
seriesActuales_en_grupos=seriesGrupos[na.omit(match(seriesActuales,seriesGrupos))]
```
las series actuales que no están en grupos, quiere decir que estas estacioes no se pueden rellenar con los grupos propuestos
```
seriesActuales_noen_grupos=seriesActuales[which(is.na(match(seriesActuales,seriesGrupos)))]
```

Guardando resultados:

```
write.table(seriesEnNomina, file="seriesEnNomina.txt",row.names = F,col.names=TRUE)
write.table(seriesNO_nomina, file="seriesNO_nomina.txt",row.names = F,col.names=TRUE)
write.table(grupos_en_seriesActuales, file="grupos_en_seriesActuales.txt",row.names = F,col.names=TRUE)
write.table(grupos_noen_seriesActuales, file="grupos_noen_seriesActuales.txt",row.names = F,col.names=TRUE)
write.table(seriesActuales_en_grupos, file="seriesActuales_en_grupos.txt",row.names = F,col.names=TRUE)
write.table(seriesActuales_noen_grupos, file="seriesActuales_noen_grupos.txt",row.names = F,col.names=TRUE)

x=strsplit(files[1],"_")[[1]][1:2]
prefijo=paste(x[1],x[2],sep="_")

for(i in seq(1,length(grupos_en_seriesActuales))){print(i)
                                                  s=paste(prefijo,"_",grupos_en_seriesActuales[i],".txt",sep="")
                                                  group=read.table(s,header=TRUE)
                                                  m=na.omit(match(rownames(group),seriesActuales))
                                                  datos_group=subset(data,select=seriesActuales[m])
                                                  print(names(datos_group))
                                                  write.table(datos_group, file=paste("datos_",prefijo,rownames(group)[1],".txt",sep=""),row.names = F,col.names=TRUE)
                                                  }

```
  
Estudio de correlaciones de los grupos  r>60Km




Parametros
```
if(opcion==1){ini=-12;fin=12}  #datos horarios de temperatura
if(opcion==4){ini=-3;fin=3}    #datos mensuales de precipitación
cor_umbral=0.8
mpc_umbral=20
```

```
ruta<-"/home/jlaraya//Documents/BaseEspejo/reportesDiariosYMensuales/grupos_datos/"
setwd(ruta)
files=dir()
files=selectSomeFiles(files,1,5,"datos",".txt") 
fechas=read.table("fechas.txt",header=T)

saneg=read.table("seriesActuales_noen_grupos.txt",header=T);saneg=as.character(saneg[,1])
pref=paste(strsplit(files[1],"_")[[1]][1],"_",strsplit(files[1],"_")[[1]][2],"_",strsplit(files[1],"_")[[1]][3],"_",sep="")
saneg2=paste(pref,saneg,".txt",sep="")

sanegAll=NULL
quantiles_antes=NULL
quantiles_despues=NULL
strt=Sys.time()
reporteAll=NULL
for(i in seq(1,length(files))){dat=read.table(files[i],header=T)
                               if(ncol(dat)<3){sanegAll=append(sanegAll,files[i]);next }
                               print(files[i])
                               dat2=acotandoDatos(fechas,dat,100,20)
                               sequ=NULL;for(jj in seq(1,ncol(dat2))){x=strsplit(names(dat2)[jj],"_")[[1]][1];sequ=append(sequ,x)}
                               fechas2=dat2[,which(sequ!="h")]
                               #fechas2=subset(dat2,select=HORA:AGNO)
                               dat2=dat2[,which(sequ=="h")]
                               if(ncol(dat2)<3){sanegAll=append(sanegAll,files[i]);next }
                               #Eliminando los -9 y outliers individuales por serie:
                               ro=remove_mv_outliers(dat2,-9,-4)
                               dat2=as.data.frame(ro[[1]]);dat2_IA=as.data.frame(ro[[2]])
                               ro2=remove_mv_outliers_group(dat2,dat2_IA,-4)
                               dat2=as.data.frame(ro2[[1]]);dat2_IA=as.data.frame(ro2[[2]])
                               #calculo de matriz de trayectoria
                               trayect_matrix=LagCorMatrix(dat2,ini,fin)
                               retardo_0=ind_00(ncol(dat2),fin)
                               print("Dimensiones de matriz de trayectoria:");print(dim(trayect_matrix))
                               #s=which(paste(names(i)[files],"_0",sep="")==names(trayect_matrix)[retardo_0])
                               reference_station=names(trayect_matrix)[retardo_0[1]]  # el nombre de la estación de referencia
                               reference_station_dat=trayect_matrix[,reference_station] #los datos de la estación de referencia
                               print("Estación de referencia:");print(reference_station)
                               c2=as.data.frame(cor(na.omit(trayect_matrix)))
                               s2=which(paste(names(dat)[1],"_0",sep="")==names(trayect_matrix))
                               bestCor2=names(c2)[which(c2[,s2]>cor_umbral & c2[,s2]<1 )]
                               bestCor2=append(reference_station,bestCor2)
                               dat2=subset(trayect_matrix,select=bestCor2)
                               print("Dimensiones de matriz de trayectoria reducidas:");print(dim(dat2))
                               if(ncol(dat2)<3){sanegAll=append(sanegAll,files[i]);next }
                               #Graficando correlaciones parciales temporales y espaciales...

                               correlaciones=corCruPar(dat2,cor_umbral,"pearson","no")
                               corCru=correlaciones[[1]];corPar=correlaciones[[2]]

                               correlaciones_dif=corCruPar(dat2,cor_umbral,"pearson","si")
                               corCruDif=correlaciones_dif[[1]];corParDif=correlaciones_dif[[2]]

                               corCruPlot=subset(corCru,select=names(corPar)) #ordenando por columnas ambas
                               corCruPlot= corCruPlot[1,]

                              corCruPlotDif=subset(corCruDif,select=names(corParDif)) #ordenando por columnas ambas
                              corCruPlotDif= corCruPlotDif[1,]

                              pdf(paste("corPar_corCru",files[i],".pdf",sep=""))
                              par(mfrow=c(2,1)) 
                              plot(corPar,main=paste("Datos sin transformación\nEstación de referencia:",names(dat2[1]),sep=""),xaxt="n",xlab="",ylab="Correlación",type="b",col="red")
                              xtick=seq(1, length(corPar),1)
                              axis(side=1, at=xtick, labels = names(corPar),las=2, cex.axis=0.7)
                              lines(corCruPlot,col="green",type="l",cex=0.8)
                              legend("topright",c("Correlación cruzada","Correlación parcial "),lty=c(1,1),lwd=c(1,1),col=c("red","green"),horiz=TRUE,cex=0.7)
                              plot(corParDif,main=paste("Datos transformados usando diferencias\nEstación de referencia:",names(dat2[1]),sep=""),xaxt="n",xlab="",ylab="Correlación",type="b",col="red")
                              xtick=seq(1, length(corParDif),1)
                              axis(side=1, at=xtick, labels = names(corParDif),las=2, cex.axis=0.7)
                              lines(corCruPlotDif,col="green",type="l",cex=0.8)
                              legend("topright",c("Correlación cruzada diferencias","Correlación parcial diferencias"),lty=c(1,1),lwd=c(1,1),col=c("red","green"),horiz=TRUE,cex=0.7)
                              boxplot(dat2,las = 2,col="yellow",main=paste("Comparación de series de retardo\nEstación de referencia:",names(dat2[1]),sep=""),cex=0.2,cex.lab=1.0,cex.axis=0.75,main="Después del control de calidad, sin relleno",xlab="",ylab="Parámetro Meteorológico")
                              dev.off()
                              dat2=as.data.frame(cbind(fechas2,dat2))
                              write.table(dat2,quote=FALSE,file=paste("Rellenar_con_ePCA_",files[i],sep=""))
                              reporte=cbind(nombre_archivo=files[i],no_fil_trayMatrix=nrow(trayect_matrix),no_fil__trayMatrix=ncol(trayect_matrix),no_fil_trayMatrix_red=nrow(dat2),no_fil__trayMatrix_red=ncol(dat2))
                              reporteAll=rbind(reporteAll,reporte)
                              }
write.table(fechas,quote=FALSE,file="fechas.txt")
write.table(reporteAll,quote=FALSE,file="reporteAll.txt")
sanegAll=append(sanegAll,saneg2)
write.table(sanegAll,quote=FALSE,file="estacionesNoRellenablesUsandoEstacionesCercanas.txt")
```


Relleno de datos







